import os

DATABASE_URL = os.getenv("DATABASE_URL")
PASSWORD_HASH_SALT = os.getenv("PASSWORD_HASH_SALT")
TOKEN_HASH_SALT = os.getenv("TOKEN_HASH_SALT")
SESSION_LIFETIME = int(os.getenv("SESSION_LIFETIME"))
SESSION_TOKEN_LENGTH = int(os.getenv("SESSION_TOKEN_LENGTH"))
